import Head from 'next/head'
import Navbar from '../components/nav'
import Image from 'next/image'

import GreyWavyBottom from '../components/greywavybottom'
import GreyWavyTop from '../components/greywavytop'

import stats_img from '../public/overdosestats.jpg'

import sectionstyles from '../styles/sections.module.scss'
import styles from '../styles/about.module.scss'

export default function About() {
  	return (
    <div>
		<Head>
			<title>Generations United - About</title>
			<meta name="description" content="Generated by create next app" />
			<link rel="icon" href="/favicon.ico" />
		</Head>

		<Navbar />

		<main>
			<GreyWavyBottom />
			<section className={sectionstyles.white_section}>
				<h2>ABOUT US..</h2>
				<p>Generations United’s movement is a public fundraising event of generations uniting nationwide, in an effort to raise awareness to the crucial role that Baking Soda plays in the illegal manufacturing of the highly addictive and deadly drugs fentanyl and crack cocaine.</p>
				<p>In addition, since Baking Soda is one of the main ingredients in both drugs, Generations United’s ultimate goal is to use strength in numbers to support a signed petition demanding Congress to pass an Act that would put restrictions on Baking Soda to curb the illegal manufacturing, use and sale of fentanyl and crack cocaine.</p>
				<br />
				<span className={sectionstyles.black_btn}><a href="https://chng.it/HKLfzFGCzJ" target="_blank" >Sign Now</a></span>
				<br /> <br />
				<Image
					className={styles.stats_img}
					src={stats_img}
					alt="overdose statistics for USA year by year organized by drug"
				/>
				<p>Fentanyl and other opioids are the leading causes of the spike in overdose deaths in the U.S. over the past 2 decades.  Two milligrams of fentanyl, which is equivalent to a few grains, is considered a deadly dose.  A fentanyl overdose is often fatal.</p>
				<p>Because crack has affected black people almost exclusively, and especially black youth, the scourge of crack has been put on a back burner.</p>
				<br />
				<span className={sectionstyles.black_btn}><a href="/learn">Learn More</a></span>
			</section>
		</main>
		<GreyWavyTop />
    </div>
  	)
}