import Head from 'next/head'
import Navbar from '../components/nav'

import GreyWavyBottom from '../components/greywavybottom'
import GreyWavyTop from '../components/greywavytop'

import sectionstyles from '../styles/sections.module.scss'

export default function Donate() {
  	return (
    <div>
		<Head>
			<title>Generations United - Donate</title>
			<meta name="description" content="Generated by create next app" />
			<link rel="icon" href="/favicon.ico" />
		</Head>

		<Navbar />

		<main>
			<GreyWavyBottom />
			<section className={sectionstyles.white_section}>
				<h2>DONATE..</h2>
				<p>Donators are given the option to have their support recognized on this website in the future.</p>
				<p>Those who show financial support will also be recieving gifts such as pins, stickers, tee-shirts, etc.. These rewards will be announced soon and will be available at upcoming events as well.</p>
				<p><em>Donations given through the prompt on change.org are not recieved by this campaign, they go to change.org directly. If you wish to support us directly, please use one of the options below...</em></p>
			
				<h3>[ GoFundMe ]</h3>
				<br />
				<span className={sectionstyles.black_btn}><a href="#">Coming Soon..</a></span>
			</section>
		</main>
		<GreyWavyTop />
    </div>
  	)
}