import React from 'react'
import Head from 'next/head'
import Image from 'next/image'

import GreyWavyTop from '../components/greywavytop'
import GreyWavyBottom from '../components/greywavybottom'
import FooterTopWave from '../components/whitewavyfootertop'
import styles from '../styles/Home.module.scss'

import logo from '../public/logotransparent-whitebakingsoda.png'


export default function Home() {
  	return (
    <div>
		<Head>
			<title>Generations United - Home</title>
			<meta name="description" content="Generated by create next app" />
			<link rel="icon" href="/favicon.ico" />
		</Head>

		<main>
			<header className={styles.heading}>
				<div>
					<Image
						className={styles.headlogo}
						src={logo} 
						alt="generations united logo" 
					/>
				</div>
				<GreyWavyTop />
			</header>

			<section className={styles.grey_section}>
				
			</section>

			<section className={styles.white_section}>
				<GreyWavyBottom />
			</section>

			<footer className={styles.footing}>
				<FooterTopWave />
			</footer>
		</main>
    </div>
  	)
}